// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWq38tvkr5r5RkfrlKqsm2IwskNQ3Sd44',
    appId: '1:101874759428:web:4efdad6affae28c45a8251',
    messagingSenderId: '101874759428',
    projectId: 'flutterecommerce-7b5ad',
    authDomain: 'flutterecommerce-7b5ad.firebaseapp.com',
    storageBucket: 'flutterecommerce-7b5ad.firebasestorage.app',
    measurementId: 'G-389W7SFZKV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1r7No5Ojk3vEhlAidJz6Wx9v4gktiQGY',
    appId: '1:101874759428:android:0a64fc26d2ce83ad5a8251',
    messagingSenderId: '101874759428',
    projectId: 'flutterecommerce-7b5ad',
    storageBucket: 'flutterecommerce-7b5ad.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWq38tvkr5r5RkfrlKqsm2IwskNQ3Sd44',
    appId: '1:101874759428:web:61b60aff377d340f5a8251',
    messagingSenderId: '101874759428',
    projectId: 'flutterecommerce-7b5ad',
    authDomain: 'flutterecommerce-7b5ad.firebaseapp.com',
    storageBucket: 'flutterecommerce-7b5ad.firebasestorage.app',
    measurementId: 'G-DR1WTSLRXV',
  );
}
