name: Build Flutter Web

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Installer Flutter version fixe et régler le safe directory
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.10'

      - name: Fix safe directory & Build Flutter Web
        run: |
          git config --global --add safe.directory /opt/hostedtoolcache/flutter/stable-3.3.10-x64
          flutter pub get
          flutter build web --release

      # Déploiement sur Vercel
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.TEAM_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
          working-directory: ./build/web
          prod: true